force-app/main/default/objects/Weather_API__mdt/Weather_API__mdt.object-meta.xml
<CustomObject>
    <label>Weather API</label>
    <pluralLabel>Weather API</pluralLabel>
</CustomObject>

force-app/main/default/objects/Weather_API__mdt/fields/Api_Id__c.field-meta.xml
<CustomField>
    <fullName>Api_Id__c</fullName>
    <label>Api_Id</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Weather_API_Request_Param__mdt/Weather_API_Request_Param__mdt.object-meta.xml
<CustomObject>
    <label>Weather API Request Param</label>
    <pluralLabel>Weather API Request Params</pluralLabel>
</CustomObject>

force-app/main/default/objects/Weather_API_Request_Param__mdt/fields/Entity_Definition__c.field-meta.xml
<CustomField>
    <fullName>Entity_Definition__c</fullName>
    <label>Entity Definition</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Weather_API_Request_Params</relationshipLabel>
    <relationshipName>Weather_API_Request_Params</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Weather_API_Request_Param__mdt/fields/Field_Definition__c.field-meta.xml
<CustomField>
    <fullName>Field_Definition__c</fullName>
    <label>Field Definition</label>
    <metadataRelationshipControllingField>Weather_API_Request_Param__mdt.Entity_Definition__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Weather_API_Request_Params</relationshipLabel>
    <relationshipName>Weather_API_Request_Params</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Weather_API_Request_Param__mdt/fields/Param_Name__c.field-meta.xml
<CustomField>
    <fullName>Param_Name__c</fullName>
    <label>Param Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Weather_API_Request_Param__mdt/fields/Weather_API__c.field-meta.xml
<CustomField>
    <fullName>Weather_API__c</fullName>
    <label>Weather API</label>
    <referenceTo>Weather_API__mdt</referenceTo>
    <relationshipLabel>Weather API Request Params</relationshipLabel>
    <relationshipName>Weather_API_Request_Params</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Weather_Setting__c/Weather_Setting__c.object-meta.xml
<CustomObject>
    <label>Weather Setting</label>
    <nameField>
        <label>Weather Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WeatherSetting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/WeatherAPIService.cls
public with sharing class WeatherAPIService {
    public static WeatherWrapper getWeather(Weather_Setting__c setting){
        Http httpClient = new Http();
        HttpRequest req = new HttpRequest();
        req.setMethod('GET');
        String url = urlReturn('Weather_API', setting);
        req.setEndpoint(url);
        HTTPResponse res = httpClient.send(req);
        WeatherWrapper wr = WeatherWrapper.parseJSON(res.getBody());
        System.debug(wr);
        return wr;
    }

    public static String urlReturn(String requestName, Weather_Setting__c setting){
        Weather_API__mdt weatherApi = [
            SELECT Id, Api_Id__c, DeveloperName, Endpoint__c, 
            (SELECT Id, Param_Name__c, Entity_Definition__r.QualifiedApiName,  Field_Definition__r.QualifiedApiName, Param_Value__c 
            FROM Weather_API_Request_Params__r) 
            FROM Weather_API__mdt
            WHERE DeveloperName =: requestName
        ];
        String returnUrlEndpoint = weatherApi.Endpoint__c;
        List<String> params = new List<String>();
        System.debug(setting);
        for (Weather_API_Request_Param__mdt param : weatherApi.Weather_API_Request_Params__r) {
            String urlParamValue = '';
            if (String.isNotBlank(param.Param_Value__c)) {
                urlParamValue = param.Param_Value__c;
            }else if (param.Entity_Definition__r.QualifiedApiName == String.valueOf(Weather_Setting__c.SObjectType)) {
                urlParamValue = (String)setting.get(param.Field_Definition__r.QualifiedApiName); 
            }
            params.add(param.Param_Name__c + '=' + urlParamValue);
        }
        returnUrlEndpoint += '?' + String.join(params,'&');
        return returnUrlEndpoint;
    }
}
/*
List<String> csvRows = new List<String>();
        SObjectType objType = Schema.getGlobalDescribe().get('Weather_Setting__c');
        Schema.DescribeSObjectResult r = objType.getDescribe();
        Map<String,Schema.SObjectField> fields = r.fields.getMap();
        for(String fieldName : r.fields.getMap().keySet()){
            Schema.DescribeFieldResult F = fields.get(fieldName).getDescribe();
            if(F.isCustom())
                csvRows.add(fieldName);
        }
        
        */