force-app/main/default/objects/Weather__c/fields/City_Name__c.field-meta.xml
<CustomField>
    <fullName>City_Name__c</fullName>
    <label>City Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Weather_Setting__c/Weather_Setting__c.object-meta.xml
<CustomObject>
    <label>Weather Setting</label>
    <nameField>
        <label>Weather Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WeatherSetting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Weather_Setting__c/fields/City_Name__c.field-meta.xml
<CustomField>
    <fullName>City_Name__c</fullName>
    <label>City Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WeatherMapControllerTest.cls
    @isTest
    private with sharing class WeatherMapControllerTest {
        @TestSetup
        private static void makeData(){
            Weather__c w = new Weather__c(
                City_Name__c = 'TestCity'
            );
            insert w;

            Weather_Setting__c ws = new Weather_Setting__c(
                City_Name__c = 'TestCity'
            );
            insert ws;
        }
    
        @isTest
        private static void getCityWeatherRecordsTest(){
            Test.startTest();
            List<Weather__c> weathers = WeatherMapController.getCityWeatherRecords('TestCity');
            Test.stopTest();
    
            System.assertEquals(1, weathers.size());
            System.assertEquals('TestCity', weathers[0].City_Name__c);
        }
    
        @isTest
        private static void getSettingsTest(){
            Test.startTest();
    
            List<Weather_Setting__c> weatherSettings = WeatherMapController.getSettings();
    
            System.assertEquals(1, weatherSettings.size());
            System.assertEquals('TestCity', weatherSettings[0].City_Name__c);
    
            Test.stopTest();
        }
    }